- name: Distribute SSH Keys
  hosts: all
  vars:
    target_user: "{{ ansible_user }}"
  tasks:
  - name: Transfer trusted keys for admin
    become: true
    ansible.posix.authorized_key:
      user: admin
      state: present
      key: '{{ item }}'
    loop:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOZJFz4J03b9gTiglxNzR2oiWqFNhPxPO+eq7DHl+fIC robin

  - name: Transfer trusted keys for ansible
    become: true
    ansible.posix.authorized_key:
      user: ansible
      state: present
      key: '{{ item }}'
    loop:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOZJFz4J03b9gTiglxNzR2oiWqFNhPxPO+eq7DHl+fIC robin
