collections:
  - name: hetzner.hcloud
    version: ">=6.5,<7"
  - name: ansible.posix
    version: ">=2.1,<3"
  - name: community.crypto
    version: ">=3.1,<4"
  - name: community.docker
    version: ">5.0.4,<6"
