$ANSIBLE_VAULT;1.1;AES256
62316566336138636365656430323462623034393661306133323366623930666430336666383934
6536356261666461313864633561666636373664623334330a633639346664666562646664616131
30356537643564373062356230383863356562383361323464653364613338383730326139306262
3366346265356636340a396561333738323964666630643932653762333534323864353332373762
31666666646633643531303136353633363333363337653566326563633538393761656633666265
63633233633336363533363132346638323365353566313938336265303936373736343962666432
33623461616239373165303766366433326234653538613633633064646563633637663038326339
61653339313463626537386537373931613238343031346132393733653431343866633933343632
63613233386462366364373830663239633137643935633230383031303939393931633531646166
31396539393161376436626339363238643763666665663136333334666334646131313161646462
33343737303733643766336164653661616230343932633630663439336132356438326666303230
35343830373231373331
